name: Upload to Tencent COS
on:
  workflow_run:
    workflows: ["Regenerate PluginMaster"]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Tencent Cloud COS Action
      uses: TencentCloud/cos-action@v1
      with:
        secret_id: ${{ secrets.SECRET_ID }}
        secret_key: ${{ secrets.SECRET_KEY }}
        cos_bucket: ${{ secrets.BUCKET }}
        cos_region: ${{ secrets.REGION }}
        local_path: /
        remote_path: /
        clean: true
